#!/usr/bin/env bash
# sim/setup_sim.sh
# Bootstrap script — run ONCE before bringing up simulated sites.
#
# What it does:
#   1. Creates a 'sim' namespace in headscale (if not present)
#   2. Generates reusable pre-auth keys for each site
#   3. Writes the keys into sim/site-envs/site-XX.env
#   4. Registers each simulated camera in the hub DB via the cameras API
#   5. NVR nodes auto-register on first heartbeat (zero-touch provisioning)
#
# Usage:
#   cd /opt/surv-learn/sim
#   bash setup_sim.sh
#
# Requires: docker, curl, jq

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

HUB_API="http://10.44.0.209:8002"
HEADSCALE_DOMAIN="vpn.sarvanetra.bsnl.co.in"
HUB_COMPOSE_DIR="/opt/surv-learn/surv"
HEADSCALE_NS="sim"

CAMERAS_PER_SITE=3
SITES=(01 02 03)
RTSP_PORTS=(9554 9555 9556)
HLS_PORTS=(9888 9889 9890)
MGMT_PORTS=(9901 9902 9903)

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERR]${NC}   $*"; exit 1; }

# ── Helpers ───────────────────────────────────────────────────────────────────
headscale_cmd() {
  docker compose -f "$HUB_COMPOSE_DIR/docker-compose.yml" \
    exec -T headscale headscale "$@"
}

# ── 1. Get hub admin JWT ───────────────────────────────────────────────────────
info "Getting hub admin JWT..."
JWT_RESP=$(curl -sf -X POST "$HUB_API/api/v1/auth/token" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "username=admin&password=admin123" 2>/dev/null || true)

if [[ -z "$JWT_RESP" ]]; then
  warn "Could not get JWT from /api/v1/auth/token. Trying /api/v1/auth/login..."
  JWT_RESP=$(curl -sf -X POST "$HUB_API/api/v1/auth/login" \
    -H "Content-Type: application/json" \
    -d '{"username":"admin","password":"admin123"}' 2>/dev/null || true)
fi

if [[ -z "$JWT_RESP" ]]; then
  warn "Hub API auth unavailable — will skip camera registration."
  warn "Run the camera registration section manually after the hub is accessible."
  HUB_TOKEN=""
else
  HUB_TOKEN=$(echo "$JWT_RESP" | jq -r '.access_token // .token // empty' 2>/dev/null || true)
  if [[ -z "$HUB_TOKEN" ]]; then
    warn "Could not parse token from response. Camera registration will be skipped."
  else
    info "Got hub JWT (${#HUB_TOKEN} chars)"
  fi
fi

# ── 2. Create headscale namespace ─────────────────────────────────────────────
info "Ensuring headscale namespace '$HEADSCALE_NS' exists..."
if headscale_cmd namespaces list 2>/dev/null | grep -q "^.*$HEADSCALE_NS"; then
  info "  Namespace '$HEADSCALE_NS' already exists."
else
  headscale_cmd namespaces create "$HEADSCALE_NS" 2>/dev/null || \
  headscale_cmd users create "$HEADSCALE_NS" 2>/dev/null || \
  warn "Could not create namespace (may already exist)"
fi

# ── 3. Generate pre-auth keys + write env files ───────────────────────────────
mkdir -p "$SCRIPT_DIR/site-envs"

for idx in "${!SITES[@]}"; do
  SITE_NUM="${SITES[$idx]}"
  SITE_CODE="SITE${SITE_NUM}"
  RTSP_PORT="${RTSP_PORTS[$idx]}"
  HLS_PORT="${HLS_PORTS[$idx]}"
  MGMT_PORT="${MGMT_PORTS[$idx]}"
  ENV_FILE="$SCRIPT_DIR/site-envs/site-${SITE_NUM}.env"

  info "Generating pre-auth key for $SITE_CODE..."
  KEY_OUTPUT=$(headscale_cmd preauthkeys create \
    -n "$HEADSCALE_NS" \
    --reusable \
    --expiration 720h 2>&1) || \
  KEY_OUTPUT=$(headscale_cmd preauthkeys create \
    --namespace "$HEADSCALE_NS" \
    --reusable \
    --expiration 720h 2>&1)

  PREAUTH_KEY=$(echo "$KEY_OUTPUT" | grep -oP '[a-f0-9]{40,}' | tail -1)
  if [[ -z "$PREAUTH_KEY" ]]; then
    warn "Could not parse pre-auth key for $SITE_CODE. Using placeholder."
    PREAUTH_KEY="REPLACE_WITH_KEY_$(date +%s)"
  else
    info "  Key for $SITE_CODE: ${PREAUTH_KEY:0:12}..."
  fi

  cat > "$ENV_FILE" <<EOF
# site-envs/site-${SITE_NUM}.env — auto-generated by setup_sim.sh
SITE_CODE=${SITE_CODE}
SITE_NUM=${SITE_NUM}
ENROLLMENT_PREAUTH_KEY=${PREAUTH_KEY}
RTSP_PORT=${RTSP_PORT}
HLS_PORT=${HLS_PORT}
MGMT_PORT=${MGMT_PORT}
CAMERAS_PER_SITE=${CAMERAS_PER_SITE}
HUB_API_URL=http://10.44.0.209:8002/api/v1
HEADSCALE_DOMAIN=${HEADSCALE_DOMAIN}
EOF
  info "  Written: $ENV_FILE"

  # ── 4. Register simulated cameras in hub DB ──────────────────────────────
  if [[ -n "$HUB_TOKEN" ]]; then
    for cam_n in $(seq 1 $CAMERAS_PER_SITE); do
      CAM_NUM=$(printf "%02d" $cam_n)
      CAM_ID="SIMCAM-${SITE_CODE}-${CAM_NUM}"
      CAM_IP="127.0.0.${idx}${cam_n}"  # Fake LAN IP — stream comes via RTSP from edge

      info "  Registering camera $CAM_ID..."
      RESP=$(curl -sf -X POST "$HUB_API/api/v1/cameras/" \
        -H "Authorization: Bearer $HUB_TOKEN" \
        -H "Content-Type: application/json" \
        -d "{
          \"cam_id\": \"$CAM_ID\",
          \"cam_name\": \"Sim ${SITE_CODE} Cam ${CAM_NUM}\",
          \"cam_ip\": \"$CAM_IP\",
          \"cam_port\": 8554,
          \"rtsp_url\": \"rtsp://10.44.0.209:${RTSP_PORT}/SIMCAM-${SITE_CODE}-${CAM_NUM}\",
          \"camera_model\": \"Simulated\",
          \"manufacturer\": \"Sarvanetra-Sim\",
          \"motion_active\": false,
          \"retention_days\": 7
        }" 2>&1 || true)

      if echo "$RESP" | jq -e '.cam_id' &>/dev/null; then
        info "    Registered: $CAM_ID"
      elif echo "$RESP" | grep -q "already exists\|409"; then
        info "    Already exists: $CAM_ID (ok)"
      else
        warn "    Registration response for $CAM_ID: $RESP"
      fi
    done
  else
    warn "Skipping camera registration for $SITE_CODE (no hub token)."
    warn "Run manually: POST $HUB_API/api/v1/cameras/ for SIMCAM-${SITE_CODE}-01..03"
  fi
done

# ── 5. Link cameras to NVR nodes in hub DB (NvrCameraMap) ───────────────────
# The fleet config endpoint queries NvrCameraMap to build the camera list.
# config_sync.py uses that list to register RTSP paths in MediaMTX.
# Without this step, /fleet/SITEXX/config returns cameras:[] and cameras crash-loop.
info "Linking simulated cameras to NVR nodes via register_cameras.sql..."
if docker compose -f "$HUB_COMPOSE_DIR/docker-compose.yml" exec -T postgres \
    psql -U surv sarvanetra < "$SCRIPT_DIR/register_cameras.sql" 2>&1; then
  info "  Camera-NVR mapping complete."
else
  warn "  register_cameras.sql failed — cameras may still appear in DB from earlier run."
  warn "  Check manually: docker compose -f $HUB_COMPOSE_DIR/docker-compose.yml exec postgres psql -U surv sarvanetra -c \"SELECT * FROM nvr_camera_map;\""
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}Setup complete!${NC}"
echo ""
echo "Generated env files:"
ls -1 "$SCRIPT_DIR/site-envs/"
echo ""
echo "Next steps:"
echo "  1. Generate video clips (if not done yet):"
echo "     bash $SCRIPT_DIR/generate_clips.sh"
echo ""
echo "  2. Bring up all 3 simulated sites:"
echo "     bash $SCRIPT_DIR/sim_manage.sh up"
echo ""
echo "  3. Verify camera-NVR mapping in hub DB:"
echo "     docker compose -f $HUB_COMPOSE_DIR/docker-compose.yml exec postgres psql -U surv sarvanetra -c \"SELECT n.site_code, c.cam_id FROM nvr_camera_map m JOIN nvr_node n ON n.id=m.nvr_node_id JOIN survapp_camera_master c ON c.id=m.camera_id ORDER BY 1,2;\""
echo ""
echo "  4. Verify in headscale:"
echo "     docker compose -f $HUB_COMPOSE_DIR/docker-compose.yml exec headscale headscale nodes list"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
