FROM bluenviron/mediamtx:latest-ffmpeg

RUN apk add --no-cache python3 py3-pip

RUN pip3 install --break-system-packages \
    minio \
    kafka-python

COPY scripts /scripts
RUN chmod +x /scripts/*.sh